[package]
name = "mars_reserves"
version = "1.0.0"
authors = []

[addresses]
mars_reserves = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
